# Generated by Django 2.1.5 on 2019-08-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='priec',
            new_name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='ended_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
